{
    "last_run": "2024-09-19 04:21:27",
    "status": "Error",
    "message": "HTTPConnectionPool(host='localhost', port=49467): Max retries exceeded with url: /session/71e3674f72bb4e3cfa5fd2a72d038938/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2fc9542ed0>: Failed to establish a new connection: [Errno 111] Connection refused')) (TENERIFE SUR)"
}